export { default as Login } from './Login';
export { default as Comidas } from './Comidas';
export { default as Bebidas } from './Bebidas';
export { default as Explorar } from './Explorar';
export { default as ExplorarComidas } from './ExplorarComidas';
export { default as ExplorarBebidas } from './ExplorarBebidas';
export { default as Favoritas } from './Favoritas';
export { default as Feitas } from './Feitas';
export { default as Perfil } from './Perfil';
